"use client";
import { motion } from "framer-motion";
import { Globe, FileText, BarChart3, FileDown, Layout, Shield } from "lucide-react";

const features = [
  {
    icon: Globe,
    title: "Real-time Translation",
    description:
      "Instant translation in 7 languages including Vietnamese, Spanish, and Haitian Creole. Medically accurate, patient-friendly.",
  },
  {
    icon: FileText,
    title: "Auto Clinical Notes",
    description:
      "Medical information extracted automatically. Symptoms, diagnosis, prescriptions — all captured without lifting a pen.",
  },
  {
    icon: BarChart3,
    title: "Smart Visit Summary",
    description:
      "End every call with a complete structured report ready for your records. Generated by AI, reviewed by you.",
  },
  {
    icon: FileDown,
    title: "Patient-Ready PDF",
    description:
      "Send patients home with instructions in their own language. Simple. Clear. Safe. One click to download.",
  },
  {
    icon: Layout,
    title: "Works Everywhere",
    description:
      "Google Meet, Zoom, Microsoft Teams, Webex. One extension. Every platform you already use.",
  },
  {
    icon: Shield,
    title: "HIPAA Minded",
    description:
      "Built with healthcare privacy in mind. No data stored on our servers. Everything stays in your browser.",
  },
];

export default function Features() {
  return (
    <section className="py-24 bg-white" id="features">
      <div className="max-w-7xl mx-auto px-6">
        <motion.div
          className="text-center mb-16"
          initial={{ opacity: 0, y: 20 }}
          whileInView={{ opacity: 1, y: 0 }}
          viewport={{ once: true }}
          transition={{ duration: 0.5 }}
        >
          <div className="inline-flex items-center gap-2 bg-[#ECFDF5] text-[#065F46] text-xs font-semibold px-3 py-1.5 rounded-full mb-4 border border-[#6EE7B7]">
            Features
          </div>
          <h2 className="text-4xl font-bold text-gray-900 mb-4 tracking-tight">
            Everything you need. Nothing you don&apos;t.
          </h2>
          <p className="text-lg text-gray-500 max-w-xl mx-auto">
            Built specifically for healthcare providers working with patients who have limited English proficiency.
          </p>
        </motion.div>

        <div className="grid md:grid-cols-2 lg:grid-cols-3 gap-6">
          {features.map((feature, i) => (
            <motion.div
              key={feature.title}
              className="p-6 rounded-2xl border border-gray-100 bg-[#F9FAFB] hover:border-[#6EE7B7] hover:bg-[#F0FDF4] transition-colors group"
              initial={{ opacity: 0, y: 20 }}
              whileInView={{ opacity: 1, y: 0 }}
              viewport={{ once: true }}
              transition={{ duration: 0.4, delay: i * 0.07 }}
            >
              <div className="w-10 h-10 rounded-lg bg-white border border-gray-200 flex items-center justify-center mb-4 group-hover:border-[#6EE7B7] group-hover:bg-[#ECFDF5] transition-colors">
                <feature.icon size={18} className="text-[#1D9E75]" />
              </div>
              <h3 className="font-semibold text-gray-900 mb-2">{feature.title}</h3>
              <p className="text-sm text-gray-500 leading-relaxed">{feature.description}</p>
            </motion.div>
          ))}
        </div>
      </div>
    </section>
  );
}
